chore(cd): fixed auto deploy workflow

diff --git a/.github/workflows/cd-dokku.yml b/.github/workflows/cd-dokku.yml
--- a/.github/workflows/cd-dokku.yml
+++ b/.github/workflows/cd-dokku.yml
@@ -89,9 +89,11 @@ jobs:
       - name: Run tasks after VPN connection
         run: |
           echo "VPN Connected! Now executing required commands..."
-          ssh-keyscan -H "${{ secrets.DOKKU_ADDR }}" >> ~/.ssh/known_hosts
-          git remote add dokku dokku@${{ secrets.DOKKU_ADDR }}:nbody-simulator-backend
-          git push dokku prod:master
+
+          ssh-keyscan -H "***" >> ~/.ssh/known_hosts || { echo "❌ ssh-keyscan failed"; exit 1; }
+          git remote add dokku dokku@***:nbody-simulator-backend || { echo "❌ git remote add failed"; exit 1; }
+          git push dokku prod:master || { echo "❌ git push failed"; exit 1; }
+
 
       - name: Verify VPN Connection
         if: always()
